#ifndef GAME_MODULE_H
#define GAME_MODULE_H

#include "types.h"
#include "graphics.h"
#include "data_structures.h"

typedef void(*GAMEMODULEHANDLER)(void);

typedef struct {
    GAMEMODULEHANDLER initialize;
    GAMEMODULEHANDLER destroy;
    GAMEMODULEHANDLER onEnterMain;
    GAMEMODULEHANDLER onExitMain;
    GAMEMODULEHANDLER main;
    u32 field_14;
    u32 field_18;
} GameMainCallbacks;

typedef struct {
    u32 unk0;
    u32 width;
    u32 heiht;
    u32 bitsPerPixel;
    u32 field_10;
    u32 field_14;
    u32 field_18;
    u32 field_1C;
    u32 field_20;
    u32 field_24;
    double field_28;
    double clockRateDouble;
    u64 clockRateInteger;
    u64 field_40;
    double fps;
    u32 tsc;
    u32 field_54;
    HINSTANCE hinstance;
    HWND hwnd;
    u32 exitValue;
    u32 field_64;
    u32 field_68;
    u32 field_6C;
    u32 field_70;
    void* directDrawCtx;
    void* iDirectDraw2;
    void* surface[3];
    DDSURFACEDESC surfaceDesc2[3];
    void* surface2;
    u32 field_1D0;
    IDirectDrawClipper clipper;
    u32 field_1D8;
    DDSURFACEDESC surfaceDescD3D;
    void *directDrawCtx2;
    u32 field_24C;
    DDSURFACEDESC surfaceDesc;
    List *d3ddev_list;
    void *d3dinterface;
    void *surface_d3ddev;			// IDirect3DDevice
    List *textureFormat_List;
    void *d3ddev_struct;
    void *d3dviewport;
    void *d3dmaterial;
    u32 field_2D8;
    void *d3d2interface;
    void *d3d2device;
    void *d3dviewport2;
    List *list_2E8;
    PolygonSet* polygonSet2EC;
    PolygonSet* polygonSet2F0;
    void* matrixStack1;
    void* matrixStack2;
    Matrix* cameraMatrix;
    struct graphics_instance *graphics_instance;
    u32 field_304;
    u32 field_308;
    u32 field_30C;
    u32 field_310;
    u32 field_314;
    u32 field_318;
    u32 field_31C;
    u32 field_320;
    D3DDEVICEDESC d3d_halcaps;
    D3DDEVICEDESC d3d_helcaps;
    DDCAPS_DX5 halcaps;
    DDCAPS_DX5 helcaps;
    u32 field_794;
    u32 field_798;
    TextureFormat surfaceTexture;
    u32 in_scene;
    AuxillaryGFX* hundred_array[5];
    void *applog_debug1;
    u32 applog_debug2;
    void *dxdbg_file;
    u32 field_840;
    u32 field_844;
    u32 _res_x;
    u32 _res_y;
    u32 _res_w;
    u32 _res_h;
    u32 field_858;
    u32 field_85C;
    u32 field_860;
    u32 field_864;
    u32 field_868;
    u32 field_86C;
    u32 field_870;
    u32 field_874;
    u32 field_878;
    u32 field_87C;
    u32 field_880;
    u32 field_884;
    u32 field_888;
    u32 field_88C;
    Matrix matrix_890;
    Matrix matrix_8D0;
    void *dx_sfx_something;
    List* textureListPtr;
    void* stack_918;
    u32 field_91C;
    void *_3d2d_something;
    u32 field_924;
    u32 field_928;
    u32 field_92C;
    u32 field_930;
    GraphicsDriverCallbacks *graphicsDriverCallbacks;
    void *_3dobject_pool;
    u32 field_93C;
    AuxillaryGFX *currentAuxillary;
    struct struc_81* field_944;
    u32 field_948;
    u32 field_94C;
    u32 field_950;
    u32 resWidth;
    u32 resHeight;
    u32 colorDepth;
    u32 field_960;
    u32 isFullScreen;
    u32 useGraphicsGUI;
    u32 graphicsOption;
    u32 field_970;
    u32 showCursor;
    u32 colorkey;
    u32 field_97C;
    u32 field_980;
    u32 d3d2_flag;
    u32 field_988;
    u32 field_98C;
    u32 field_990;
    u32 field_994;
    u32 matrixStackSize;
    u32 FieldOfView;
    u32 zNear;
    u32 zFar;
    u32 leftPosition;
    u32 topPosition;
    u32 randomSeed;
    char* wndNamePtr;
    char* wndClassNamePtr;
    u32 useWndClass;
    WNDCLASSA wndclass;
    u32 useDWStyle;
    u32 DWStyle;
    GameMainCallbacks mainCallbacks9F0;
    GameMainCallbacks mainCallbacksA0C;
    void *wm_activate;
    u32 field_A2C;
    u32 field_A30;
    u32 field_A34;
    u32 field_A38;
    u32 field_A3C;
    u32 field_A40;
    u32 field_A44;
    u32 field_A48;
    u32 field_A4C;
    u32 field_A50;
    u32 field_A54;
    u32 field_A58;
    u32 field_A5C;
    u32 currentGFXDriver;
    u32 field_A64;
    u32 field_A68;
    u32 field_A6C;
    u32 field_A70;
    u32 field_A74;
    u32 field_A78;
    void* GFXDriverData;
    u32 field_A80;
    u32 field_A84;
    void* createGFXDriver;
    void* externals;
    u32 nvidiaFix;
    u32 tntFix;
    u32 noRivaFix;
    u32 field_A9C;
} GameContext;

typedef struct{
    u8 dummy[0xCC];
} D3DDEVICEDESC;

typedef u32(*SRGFXDRIVER_CREATE)(GameContext*);
typedef void(*SRGFXDRIVER_DESTROY)(GameContext*);
typedef u32(*SRGFXDRIVER_LOCK)(u32);
typedef u32(*SRGFXDRIVER_UNLOCK)(u32);
typedef void(*SRGFXDRIVER_FLIP)(GameContext*);
typedef void(*SRGFXDRIVER_CLEAR)(u32, u32, u32, GameContext*);
typedef void(*SRGFXDRIVER_CLEARALL)(GameContext*);
typedef void(*SRGFXDRIVER_SETVIEWPORT)(u32, u32, u32, u32, GameContext*);
typedef void(*SRGFXDRIVER_SETBG)(ColorBGRA *, GameContext*);
typedef u32(*SRGFXDRIVER_INITPOLYGONSET)(PolygonSet*);
typedef u32(*SRGFXDRIVER_LOADGROUP)(u32, MatrixSet*, AuxillaryGFX*, PGroup*, PFilePolygonData*, PolygonSet*, GameContext*);
typedef void(*SRGFXDRIVER_SETMATRIX)(u32, Matrix*, MatrixSet*, GameContext*);
typedef void(*SRGFXDRIVER_UNLOADTEXTURE)(TextureSet*);
typedef TextureSet*(SRGFXDRIVER_LOADTEXTURE)(TextureSet*, TextureHeader*, TextureFormat*);
typedef u32(*SRGFXDRIVER_PALETTECHANGED)(u32, u32, u32, Palette*, TextureSet*);
typedef u32(*SRGFXDRIVER_WRITEPALLETTE)(u32, u32, void*, u32, Palette*, TextureSet*);
typedef struct blend_mode *(SRGFXDRIVER_BLENDMODE)(u32, GameContext*);
typedef void(SRGFXDRIVER_LIGHTPOLYGONSET)(PolygonSet*, void*);
typedef void(gfx_field_64)(u32, u32, GameContext*);
typedef void(gfx_setrenderstate)(AuxillaryGFX*, GameContext*);
typedef void(gfx_field_74)(u32, GameContext*);
typedef void(gfx_field_78)(PolygonSet*, GameContext*);
typedef void(gfx_draw_deferred)(struct struc_77 *, GameContext*);
typedef void(gfx_field_80)(GraphicsObject*, GameContext*);
typedef void(gfx_field_84)(u32, GameContext*);
typedef u32(gfx_begin_scene)(u32, GameContext*);
typedef void(gfx_end_scene)(GameContext*);
typedef void(gfx_field_90)(u32);
typedef void(SRGFXDRIVER_SETPOLYRENDER)(PolygonSet*, IndexedVertices*, GameContext*);
typedef void(SRGFXDRIVER_DRAWVERTICES)(PolygonSet*, IndexedVertices*, GameContext*);
typedef void(gfx_field_EC)(GameContext*);

typedef struct {
    SRGFXDRIVER_CREATE createDriver;
    SRGFXDRIVER_DESTROY destroyDriver;
    SRGFXDRIVER_LOCK lock;
    SRGFXDRIVER_UNLOCK unlock;
    SRGFXDRIVER_FLIP flip;
    SRGFXDRIVER_CLEAR clear;
    SRGFXDRIVER_CLEARALL clearAll;
    SRGFXDRIVER_SETVIEWPORT setViewPort;
    SRGFXDRIVER_SETBG setBackGround;
    u32 field_24;
    ColorBGRA field_28;			// ?
    u32 field_38;
    u32 field_3C;
    SRGFXDRIVER_INITPOLYGONSET initPolygonSet;
    SRGFXDRIVER_LOADGROUP loadGroup;
    SRGFXDRIVER_SETMATRIX setMatrix;
    SRGFXDRIVER_UNLOADTEXTURE;
    SRGFXDRIVER_LOADTEXTURE loadTexture;
    SRGFXDRIVER_PALETTECHANGED paletteChanged;
    gfx_write_palette *write_palette;
    gfx_blendmode *blendmode;
    gfx_light_polygon_set *light_polygon_set;
    gfx_field_64 *field_64;
    gfx_setrenderstate *setrenderstate;
    gfx_setrenderstate *_setrenderstate;
    gfx_setrenderstate *__setrenderstate;
    gfx_field_74 *field_74;
    gfx_field_78 *field_78;
    gfx_draw_deferred *draw_deferred;
    gfx_field_80 *field_80;
    gfx_field_84 *field_84;
    gfx_begin_scene *begin_scene;
    gfx_end_scene *end_scene;
    gfx_field_90 *field_90;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_flat2D;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_smooth2D;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_textured2D;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_paletted2D;
    SRGFXDRIVER_SETPOLYRENDER *_setrenderstate_paletted2D;
    SRGFXDRIVER_DRAWVERTICES drawFlat2D;
    SRGFXDRIVER_DRAWVERTICES drawSmooth2D;
    SRGFXDRIVER_DRAWVERTICES drawTextured2D;
    SRGFXDRIVER_DRAWVERTICES drawPaletted2D;
    SRGFXDRIVER_SETPOLYRENDER *setRenderState_flat3D;
    SRGFXDRIVER_SETPOLYRENDER *setRenderState_smooth3D;
    SRGFXDRIVER_SETPOLYRENDER *setRenderState_textured3D;
    SRGFXDRIVER_SETPOLYRENDER *setRenderState_paletted3D;
    SRGFXDRIVER_SETPOLYRENDER *_setRenderState_paletted3D;
    SRGFXDRIVER_DRAWVERTICES drawFlat3D;
    SRGFXDRIVER_DRAWVERTICES drawSmooth3D;
    SRGFXDRIVER_DRAWVERTICES drawTextured3D;
    SRGFXDRIVER_DRAWVERTICES drawPaletted3D;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_flatlines;
    SRGFXDRIVER_SETPOLYRENDER *setrenderstate_smoothlines;
    SRGFXDRIVER_DRAWVERTICES draw_flatlines;
    SRGFXDRIVER_DRAWVERTICES draw_smoothlines;
    gfx_field_EC *field_EC;
} GraphicsDriverCallbacks;

#endif
